args:
  sparse: 0
  learner_type: 'mlp'
  hidden_dim: [256, 512]
  rep_dim: [32, 64]
  proj_dim: [32, 64]
  dropout: [0, 0.5]
  contrast_batch_size: 0
  nlayers: 2
  i: 6

  # Structure Bootapping
  tau: [0.999, 0.9999, 0.99999] # bootstrapping decay [0.999, 0.9999, 0.99999]
  c: [5, 10, 15] # how often anchor adj is updated [5, 10, 15]

  # GCL Module -Augmentation
  maskfeat_rate_learner: [0.2, 0.5, 0.8]
  maskfeat_rate_anchor: [ 0.2, 0.5, 0.8]
  dropedge_rate: [0.25, 0.5, 0.75]

  # GSL Module
  k: [20, 30, 40] # top-k neighbours taken in sparseification 
  sim_function: 'cosine'
  activation_learner: 'relu'
  gamma: [0.7, 0.8, 0.9]




