args:
  max_epoch: 2500
  patience: 250
  learning_rate: 0.001
  weight_decay: 0.0
  architecture: 64
  cluster_size_regularization: 1.0
  dropout_rate: 0.5
  recon_loss_reg: 1.0
  con_loss_reg: 1.0
  beta: 0.99

trainer:
  only_testing: True