model: 'daegc'
dataset: 'cora'
special_training: 
  split_addition_percentage: False

trainer:
  gpu: "0"
  show_config: True
  calc_time: False
  results_path: './results/'
  load_hps_path: './found_hps/'
  data_path: './data/'
  load_existing_test: False
  only_testing: False

  test_metrics: ['f1', 'nmi', 'modularity', 'conductance']
  valid_metrics: ['f1', 'nmi', 'modularity', 'conductance']
  validate_every_nepochs: 5
  n_trials_hyperopt: 1
  max_n_pruned: 20

  training_to_testing_split: 0.8
  train_to_valid_split: 0.8
  split_scheme: "drop_edges"

  split_addition_percentage: False

  retrain_on_each_dataset: False
  model_save_location: './models/'
  model_resolution_metric: 'nmi'
  finetuning_new_dataset: False 
  save_model: False
  same_init_hpo: False

  logger:
    log_wandb: False
    project: 'ugle'
    entity: 'phd-keep-learning'
    log_cmd: 50

args:
  n_clusters: null
  random_seed: 42
  kmeans_init: 30
  max_epoch: 5000
  patience: [25, 100, 500, 1000]
  learning_rate: [0.05, 0.01, 0.005, 0.001, 0.0005, 0.0001]
  weight_decay: [0.05, 5e-3, 0.0005, 0.]


