model: 'daegc'
dataset: 'cora'

trainer:
  gpu: "0"
  show_config: False
  results_path: './results/'
  load_hps_path: './found_hps/'
  data_path: './data/'
  models_path: './models/'
  load_existing_test: False
  save_hpo_study: False
  save_model: False

  # hyperparameter options
  test_metrics: ['f1', 'nmi', 'modularity', 'conductance']
  valid_metrics: ['f1', 'nmi', 'modularity', 'conductance']
  validate_every_nepochs: 5
  n_trials_hyperopt: 1
  max_n_pruned: 20
  suggest_hps_from_previous_seed: False

  training_to_testing_split: 0.2
  train_to_valid_split: 0.2
  split_scheme: 'drop_edges' # one of drop_edges, split_edges, all_edges, no_edges (see ugle.datasets.split_adj() for more info)

  # logging options
  calc_time: True
  calc_memory: False
  log_interval: 5

args:
  n_clusters: null
  random_seed: 42
  kmeans_init: 30
  max_epoch: 5000
  patience: [25, 100, 500, 1000]
  learning_rate: [0.05, 0.01, 0.005, 0.001, 0.0005, 0.0001]
  weight_decay: [0.05, 5e-3, 0.0005, 0.]


