args:
  max_epoch: 400
  patience: 400
  learning_rate: 0.0001
  weight_decay: 1e-5

  num_hidden: 512
  num_layers: 2
  tau: 1.0
  tau_knbrs: 1.0
  loss_instance: 1.0
  loss_knbrs: 1.0
  loss_coef: 1.0
  rec_loss: 0.1
