seeds: [42]
datasets: ['cora']
algorithms: ['daegc_default', 'dgi_default', 'dmon_default', 'grace_default', 'mvgrl_default', 'selfgnn_default', 'sublime_default', 'bgrl_default', 'vgaer_default', 'cgac_default']

study_override_cfg:
  trainer:
    calc_time: True
    calc_memory: True
    test_metrics: ['f1', 'nmi', 'modularity', 'conductance']
    valid_metrics: [ 'f1', 'nmi', 'modularity', 'conductance']
