seeds: [42, 24, 976, 12345, 98765, 7, 856, 90, 672, 785]
datasets: ['synth_disjoint_2']
algorithms: ['dgi']

study_override_cfg:
  trainer:
    show_config: False
    load_existing_test: False
    calc_time: False
    n_trials_hyperopt: 10
    test_metrics: ['f1', 'nmi', 'modularity', 'conductance']
    valid_metrics: [ 'f1', 'nmi', 'modularity', 'conductance' ]
    gpu: '0'
    results_path: './synth/' # results path for saved results