seeds: [785]
datasets: ["cora"]
algorithms: ["dmon_default"]
dataset_algo_combinations: null
run_cpu_fallback: False
special_training: 
  split_addition_percentage: False
  retrain_on_each_dataset: False

study_override_cfg:
  trainer:
    n_trials_hyperopt: 2
    results_path: './results/failing/'

    show_config: False
    load_existing_test: False
    only_testing: True

    test_metrics: ['f1', 'nmi', 'modularity', 'conductance']
    valid_metrics: ['modularity', 'conductance']
    gpu: -1
    split_scheme: 'drop_edges'
    train_to_valid_split: 1.0
    training_to_testing_split: 1.0
    suggest_hps_from_previous_seed: True
    calc_time: True
    calc_memory: False
    log_interval: 5

  args:
    max_epoch: 10