seeds: [785]
datasets: []
algorithms: []
dataset_algo_combinations: ["cora_dmon_default"]
run_cpu_fallback: False
special_training: 
  split_addition_percentage: False
  retrain_on_each_dataset: False

study_override_cfg:
  trainer:
    n_trials_hyperopt: 1
    results_path: './results/failing/'
    save_hpo_study: False
    only_testing: True

    show_config: False
    load_existing_test: False
    calc_time: False

    test_metrics: ['f1', 'nmi', 'modularity', 'conductance']
    valid_metrics: ['modularity', 'conductance']
    gpu: -1
    split_scheme: 'drop_edges'
    train_to_valid_split: 1.0
    training_to_testing_split: 1.0
    suggest_hps_from_previous_seed: True

  args:
    max_epoch: 5