seeds: [785, 42, 236]
datasets: []
algorithms: []
dataset_algo_combinations: ["cora_dmon"]
run_cpu_fallback: False
special_training: 
  split_addition_percentage: False
  retrain_on_each_dataset: False

study_override_cfg:
  trainer:
    n_trials_hyperopt: 2
    results_path: './results/failing/'

    show_config: False
    load_existing_test: False
    calc_time: False

    test_metrics: ['f1', 'nmi', 'modularity', 'conductance']
    valid_metrics: ['modularity', 'conductance']
    gpu: -1
    suggest_hps_from_previous_seed: True

  args:
    max_epoch: 10