save_test_cfg: False

args:
  gpu: 0
  save_path: './saves/'
  results_path: './results/'
  testing: False
  test_split: 0.5
  n_trials: 10
  keep_connected: False
  k_splits: 1
  training_split: 0.8
  log_interval: 10