seeds: [42, 24]
datasets: ['cora']
algorithms: ['daegc']
run_cpu_fallback: False
special_training: 
  split_addition_percentage: False
  retrain_on_each_dataset: False

study_override_cfg:
  trainer:
    n_trials_hyperopt: 3
    results_path: './results/'
    only_testing: False

    show_config: False
    load_existing_test: False
    calc_time: False

    test_metrics: ['f1', 'nmi', 'modularity', 'conductance']
    valid_metrics: ['modularity', 'conductance']
    gpu: '0'
    split_scheme: 'drop_edges'
    train_to_valid_split: 1.0
    training_to_testing_split: 1.0

    same_init_hpo: True

  args:
    max_epoch: 50
    patience: 25
    learning_rate: 0.05
    weight_decay: 0.
  
