seeds: [42]
datasets: ['amac']
algorithms: ['daegc_test']

study_override_cfg:
  args:
    random_seed: null

  trainer:
    trainer:
    save_test_cfg: False
    test_metrics: ['f1', 'nmi', 'modularity', 'conductance']
    gpu: '0'
    n_trials_hyperopt: 1