seeds: [42, 24]
datasets: ['cora']
algorithms: ['daegc']
run_cpu_fallback: False

study_override_cfg:
  trainer:
    n_trials_hyperopt: 3
    results_path: './results/'
    only_testing: False

    show_config: False
    load_existing_test: False
    calc_time: False

    test_metrics: ['f1', 'nmi', 'modularity', 'conductance']
    valid_metrics: ['modularity', 'conductance']
    gpu: '0'

    same_init_hpo: False

  args:
    max_epoch: 50
    patience: 25
    learning_rate: 0.05
    weight_decay: 0.
  
