seeds: [42, 24]
datasets: ['citeseer', 'cora', 'wisc', 'texas', 'amac', 'dblp', 'pubmed', 'cornell']
algorithms: ['dgi_default', 'daegc_default', 'grace_default', 'sublime_default', 'bgrl_default', 'vgaer_default']
dataset_algo_combinations: null
run_cpu_fallback: False
special_training: 
  split_addition_percentage: False
  retrain_on_each_dataset: False

study_override_cfg:
  trainer:
    n_trials_hyperopt: 1
    results_path: './results/testing/'

    only_testing: True
    show_config: False
    load_existing_test: False

    calc_time: True
    calc_memory: True

    test_metrics: ['f1', 'nmi', 'modularity', 'conductance']
    valid_metrics: ['modularity', 'conductance']
    gpu: '1'
    split_scheme: 'drop_edges'
    train_to_valid_split: 1.0
    training_to_testing_split: 1.0
